name: Trigger Target Workflow
on:
 workflow_dispatch:
   inputs:
     environment:
       type: string
       default: DEV
       required: false
 push:
   branches:
     - main
jobs:
 trigger-workflow:
   runs-on: ubuntu-latest
   steps:
     - name: Trigger Workflow Dispatch
       run: |
         curl -X POST \
           -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
           https://api.github.com/repos/danielratiu/FASTEN_Demo/dispatches \
           -d '{
              "event_type": "custom_event",
              "client_payload": {
                "ref": "test_validation"
              }
            }'
